IF SCHEMA_ID(N'platform') IS NULL
    EXEC(N'CREATE SCHEMA platform AUTHORIZATION dbo');

IF SCHEMA_ID(N'identity') IS NULL
    EXEC(N'CREATE SCHEMA identity AUTHORIZATION dbo');

IF SCHEMA_ID(N'messaging') IS NULL
    EXEC(N'CREATE SCHEMA messaging AUTHORIZATION dbo');

IF SCHEMA_ID(N'audit') IS NULL
    EXEC(N'CREATE SCHEMA audit AUTHORIZATION dbo');
